// Paper dimensions in mm
export const PAPER_SIZES = {
  A4: { name: 'A4 (210 × 297 mm)', width: 210, height: 297 },
  A3: { name: 'A3 (297 × 420 mm)', width: 297, height: 420 },
  LETTER: { name: 'US Letter (215.9 × 279.4 mm)', width: 215.9, height: 279.4 },
  CUSTOM: { name: 'กำหนดขนาดเอง (Custom)', width: 210, height: 297 },
};

// Built-in Presets
export const DEFAULT_PRESETS = [
  {
    id: 'pdf-9x13-standard',
    name: 'ต้นฉบับในไฟล์แนบ (9 × 13 = 117 ดวง/แผ่น A4)',
    description: 'ขนาดพอดีแผ่น A4 เหมือนในตัวอย่าง 9 คอลัมน์ 13 แถว',
    paper: 'A4',
    paperWidth: 210,
    paperHeight: 297,
    columns: 9,
    rows: 13,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 8,
    marginRight: 8,
    colGap: 0,
    rowGap: 0,
    showBorder: true,
    borderStyle: 'solid', // solid, dashed, dotted, none
    borderColor: '#cbd5e1',
    borderWidth: 0.5,
    borderRadius: 0,
    qrSizePercent: 82,
    fontSizePt: 6.2,
    fontWeight: '600',
    fontFamily: 'monospace',
    textMarginTop: 1,
    showSerialText: true,
    textPosition: 'below', // 'below' | 'above'
    headerText: '',
    headerFontSizePt: 5,
    qrErrorCorrection: 'M',
    qrColorDark: '#000000',
    qrColorLight: '#ffffff',
  },
  {
    id: 'std-5x10-50',
    name: 'สติกเกอร์ขนาดกลาง (5 × 10 = 50 ดวง/แผ่น A4)',
    description: 'เหมาะสำหรับกล่องสินค้าขนาดกลาง ตัวอักษรและ QR Code ใหญ่ขึ้น',
    paper: 'A4',
    paperWidth: 210,
    paperHeight: 297,
    columns: 5,
    rows: 10,
    marginTop: 12,
    marginBottom: 12,
    marginLeft: 10,
    marginRight: 10,
    colGap: 0,
    rowGap: 0,
    showBorder: true,
    borderStyle: 'solid',
    borderColor: '#cbd5e1',
    borderWidth: 0.5,
    borderRadius: 2,
    qrSizePercent: 80,
    fontSizePt: 8,
    fontWeight: '600',
    fontFamily: 'monospace',
    textMarginTop: 1.5,
    showSerialText: true,
    textPosition: 'below',
    headerText: '',
    headerFontSizePt: 6,
    qrErrorCorrection: 'M',
    qrColorDark: '#000000',
    qrColorLight: '#ffffff',
  },
  {
    id: 'std-3x8-24',
    name: 'สติกเกอร์มาตรฐาน (3 × 8 = 24 ดวง/แผ่น A4)',
    description: 'ขนาดสติกเกอร์ยอดนิยมสำหรับแปะสินค้าทั่วไป',
    paper: 'A4',
    paperWidth: 210,
    paperHeight: 297,
    columns: 3,
    rows: 8,
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 10,
    marginRight: 10,
    colGap: 0,
    rowGap: 0,
    showBorder: true,
    borderStyle: 'solid',
    borderColor: '#cbd5e1',
    borderWidth: 0.5,
    borderRadius: 3,
    qrSizePercent: 78,
    fontSizePt: 10.5,
    fontWeight: '700',
    fontFamily: 'monospace',
    textMarginTop: 2,
    showSerialText: true,
    textPosition: 'below',
    headerText: '',
    headerFontSizePt: 7,
    qrErrorCorrection: 'M',
    qrColorDark: '#000000',
    qrColorLight: '#ffffff',
  },
  {
    id: 'mini-10x15-150',
    name: 'สติกเกอร์มินิ (10 × 15 = 150 ดวง/แผ่น A4)',
    description: 'สำหรับชิ้นงานขนาดเล็กมาก Micro parts / PCB',
    paper: 'A4',
    paperWidth: 210,
    paperHeight: 297,
    columns: 10,
    rows: 15,
    marginTop: 8,
    marginBottom: 8,
    marginLeft: 6,
    marginRight: 6,
    colGap: 0,
    rowGap: 0,
    showBorder: true,
    borderStyle: 'solid',
    borderColor: '#e2e8f0',
    borderWidth: 0.4,
    borderRadius: 0,
    qrSizePercent: 84,
    fontSizePt: 5.2,
    fontWeight: '600',
    fontFamily: 'monospace',
    textMarginTop: 0.8,
    showSerialText: true,
    textPosition: 'below',
    headerText: '',
    headerFontSizePt: 4.5,
    qrErrorCorrection: 'L',
    qrColorDark: '#000000',
    qrColorLight: '#ffffff',
  },
];

export const INITIAL_DATA_CONFIG = {
  mode: 'sequential', // 'sequential', 'manual', 'excel', 'random'
  batchName: 'Lot สินค้า ' + new Date().toISOString().slice(0, 10),
  
  // Sequential settings
  startNumber: '0673304866',
  count: 117,
  prefix: '',
  suffix: '',
  digits: 10, // padding length
  step: 1,
  
  // Manual settings
  manualList: '0673304866\n0673304874\n0673304884\n0673304886\n0673304899\n0673304902\n0673304905\n0673304916\n0673304969',
  
  // Random settings
  randomCount: 117,
  randomLength: 10,
  randomType: 'numeric', // 'numeric', 'alphanumeric', 'uppercase'
  randomPrefix: '',
  
  // QR content template
  qrContentType: 'serial', // 'serial', 'url', 'custom'
  qrUrlTemplate: 'https://mainon.com/verify?sn={SERIAL}',
  qrCustomTemplate: 'SN:{SERIAL}',
};
